---
# tasks file for ssh
- name: Include OS specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

- name: Check sshd local config file presence
  ansible.builtin.stat:
    path: "{{ ssh_config_file }}"
  register: sshd_local_config_file
  when:
    - ssh_config_file is defined
  tags:
    - ssh
    - stat

- name: Touch sshd local config file
  ansible.builtin.file:
    path: "{{ ssh_config_file }}"
    state: touch
    mode: 0644
  when:
    - ssh_config_file is defined
    - not sshd_local_config_file.stat.exists
  tags:
    - ssh
    - stat

- name: Port in default config file
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^[#\s]*Port\s+.*$'
    line: '#Port 22'
    backup: true
    validate: /usr/sbin/sshd -t -f %s
  when:
    - ssh_port is not defined
      or ( ssh_port is defined and ssh_port == 22 )
      or ssh_config_file is defined
  notify: SSH restart
  tags:
    - ssh
    - port

- name: Port in local config file
  ansible.builtin.lineinfile:
    path: "{{ ssh_config_file | default('/etc/ssh/sshd_config') }}"
    regexp: '^[#\s]*Port\s+.*$'
    line: 'Port {{ ssh_port }}'
    backup: true
    validate: /usr/sbin/sshd -t -f %s
  when:
    - ssh_port is defined
    - ssh_config_file is defined
  notify: SSH restart
  tags:
    - ssh
    - port

- name: PasswordAuthentication
  ansible.builtin.lineinfile:
    path: "{{ ssh_config_file | default('/etc/ssh/sshd_config') }}"
    regexp: '^[#\s]*PasswordAuthentication\s+.*$'
    line: 'PasswordAuthentication {{ ssh_passwordauthentication | lower() }}'
    backup: true
    validate: /usr/sbin/sshd -t -f %s
  when:
    - ssh_passwordauthentication is defined
    - ssh_passwordauthentication | lower() in [ 'yes', 'no' ]
  notify: SSH restart
  tags:
    - ssh
    - passwordauthentication

- name: Gssapiauthentication
  ansible.builtin.lineinfile:
    path: "{{ ssh_config_file | default('/etc/ssh/sshd_config') }}"
    regexp: '^[#\s]*GSSAPIAuthentication\s+.*$'
    line: 'GSSAPIAuthentication {{ ssh_gssapiauthentication | lower() }}'
    backup: true
    backrefs: true
    validate: /usr/sbin/sshd -t -f %s
  when:
    - ssh_gssapiauthentication is defined
    - ssh_gssapiauthentication | lower() in [ 'yes', 'no' ]
  notify: SSH restart
  tags:
    - ssh
    - gssapiauthentication

- name: SFTP
  ansible.builtin.lineinfile:
    # Subsystem can't be outside main sshd_config
    path: /etc/ssh/sshd_config
    regexp: '^[#\s]*Subsystem\s+sftp.*$'
    line: '{{ ssh_sftp_command }}'
    backup: true
    backrefs: true
    validate: /usr/sbin/sshd -t -f %s
  when:
    - ssh_sftp_command is defined
  notify: SSH restart
  tags:
    - ssh
    - sftp
