---
# tasks file for ssh
- include_tasks: "{{ ansible_os_family }}.yml"

- name: port
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[#\s]*Port\s+.*$'
    line: '#Port 22'
    backup: yes
    validate: /usr/sbin/sshd -t -f %s
  when: ssh_port is not defined or ( ssh_port is defined and ssh_port == 22 )
  notify: ssh restart
  tags:
    - ssh
    - port

- name: port
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[#\s]*Port\s+.*$'
    line: 'Port {{ ssh_port }}'
    backup: yes
    validate: /usr/sbin/sshd -t -f %s
  when:
    - ssh_port is defined
  notify: ssh restart
  tags:
    - ssh
    - port

- name: passwordauthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[#\s]*PasswordAuthentication\s+.*$'
    line: 'PasswordAuthentication {{ ssh_passwordauthentication | lower() }}'
    backup: yes
    validate: /usr/sbin/sshd -t -f %s
  when:
    - ssh_passwordauthentication is defined
    - ssh_passwordauthentication | lower() in [ 'yes', 'no' ]
  notify: ssh restart
  tags:
    - ssh
    - passwordauthentication

- name: gssapiauthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[#\s]*GSSAPIAuthentication\s+.*$'
    line: 'GSSAPIAuthentication {{ ssh_gssapiauthentication | lower() }}'
    backup: yes
    backrefs: yes
    validate: /usr/sbin/sshd -t -f %s
  when:
    - ssh_gssapiauthentication is defined
    - ssh_gssapiauthentication | lower() in [ 'yes', 'no' ]
  notify: sshd restart
  tags:
    - ssh
    - gssapiauthentication

- name: sftp
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[#\s]*Subsystem\s+sftp.*$'
    line: '{{ ssh_sftp_command }}'
    backup: yes
    backrefs: yes
    validate: /usr/sbin/sshd -t -f %s
  when:
    - ssh_sftp_command is defined
  notify: ssh restart
  tags:
    - ssh
    - sftp
...
