---
# tasks file for syncthing
- name: apt_key
  apt_key:
    url: '{{ st_key_url }}'
  tags:
    - syncthing
    - key

- name: apt_repository
  apt_repository:
    filename: 'syncthing'
    repo: 'deb https://apt.syncthing.net/ syncthing stable'
  tags:
    - syncthing
    - repo

- name: preferences
  template:
    src: 'apt.preferences.j2'
    dest: '/etc/apt/preferences.d/syncthing'
  tags:
    - syncthing
    - preferences

- name: package
  package:
    name: '{{ st_packages }}'
    force_apt_get: yes
  tags:
    - syncthing
    - package

- name: systemd unit
  template:
    src: systemd.j2
    dest: /etc/systemd/system/syncthing@.service
  notify: restart
  tags:
    - syncthing
    - systemd

- name: user
  user:
    name: 'syncthing'
    comment: 'Syncthing'
    system: yes
    createhome: yes
  when: st_user == 'syncthing'
  tags:
    - syncthing
    - user

- name: service
  systemd:
    name: '{{ item }}@{{ st_user }}.service'
    enabled: yes
    state: started
    daemon_reload: yes
  with_items: '{{ st_packages }}'
  tags:
    - syncthing
    - services

- name: sysctl
  template:
    src: 'st_sysctl.conf.j2'
    dest: '{{ st_sysctl_file }}'
  when:
    - st_max_user_watches is defined
  notify:
    - apply sysctl settings
  tags:
    - syncthing
    - sysctl
...
