---
# tasks file for ssh
- name: permitrootlogin
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[#\s]*PermitRootLogin\s+.*$'
    line: '#PermitRootLogin prohibit-password'
    backup: yes
    validate: /usr/sbin/sshd -t -f %s
  when: ssh_permitrootlogin is not defined or ( ssh_permitrootlogin|lower() == 'prohibit-password' )
  notify: ssh restart
  tags:
    - ssh
    - permitrootlogin

- name: passwordauthentication
  # #PasswordAuthentication *
  # will be replaced with
  # PasswordAuthentication no
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[#\s]*PasswordAuthentication\s+.*$'
    line: 'PasswordAuthentication {{ ssh_passwordauthentication | lower() }}'
    backup: yes
    validate: /usr/sbin/sshd -t -f %s
  when:
    - ssh_passwordauthentication is defined
    - ssh_passwordauthentication|lower() in ['yes','no']
  notify: ssh restart
  tags:
    - ssh
    - passwordauthentication
...
