---
# tasks file for syncthing

- block:
  - name: apt_key
    apt_key:
      url: '{{ syncthing_key_url }}'
    tags:
      - syncthing
      - key
      - apt_key

  - name: apt_repository
    apt_repository:
      filename: 'syncthing'
      repo: '{{ syncthing_apt_repository }}'
      update_cache: true
    tags:
      - syncthing
      - repo
      - repository
      - apt_repository

  - name: preferences
    template:
      src: 'apt.preferences.j2'
      dest: '/etc/apt/preferences.d/syncthing'
    tags:
      - syncthing
      - preferences
  when:
    - syncthing_origin is defined
    - syncthing_origin == "upstream"

- name: package
  package:
    name: '{{ syncthing_packages }}'
  tags:
    - syncthing
    - package

- name: systemd unit
  template:
    src: systemd.j2
    dest: /etc/systemd/system/syncthing@.service
  notify: restart
  tags:
    - syncthing
    - systemd

- name: user
  user:
    name: 'syncthing'
    comment: 'Syncthing'
    system: yes
    createhome: yes
  when: syncthing_user == 'syncthing'
  tags:
    - syncthing
    - user

- name: service
  systemd:
    name: '{{ item }}@{{ syncthing_user }}.service'
    enabled: yes
    state: started
    daemon_reload: yes
  with_items: '{{ syncthing_packages }}'
  tags:
    - syncthing
    - services

- name: sysctl
  template:
    src: 'syncthing_sysctl.conf.j2'
    dest: '{{ syncthing_sysctl_file }}'
  when:
    - syncthing_max_user_watches is defined
  notify:
    - apply sysctl settings
  tags:
    - syncthing
    - sysctl
...
