---
# tasks file for syncthing
- name: Upstream
  tags:
    - syncthing
    - apt
  when:
    - syncthing_origin is defined
    - syncthing_origin == 'upstream'
  block:
    - name: APT key
      ansible.builtin.get_url:
        url: "{{ syncthing_key_url }}"
        dest: "{{ syncthing_key_dest }}"
        mode: 0644
      # https://github.com/ansible/ansible/issues/65687
      when: not ansible_check_mode
      tags:
        - key

    - name: APT repository
      ansible.builtin.template:
        src: syncthing.list.j2
        dest: /etc/apt/sources.list.d/syncthing.list
        mode: 0644
      tags:
        - repository

- name: Package
  ansible.builtin.package:
    name: "{{ syncthing_packages }}"
    update_cache: true
  tags:
    - syncthing
    - package

- name: User systemd unit
  tags:
    - syncthing
    - systemd
  when:
    - syncthing_systemd_user is defined
    - syncthing_systemd_user
  block:
    - name: File
      ansible.builtin.file:
        path: "~{{ syncthing_user }}/.config/systemd/user"
        state: directory
        owner: "{{ syncthing_user }}"
        group: "{{ syncthing_user }}"
        mode: 0755
      tags:
        - directory

    - name: Template
      ansible.builtin.template:
        src: systemd.user.j2
        dest: "~{{ syncthing_user }}/.config/systemd/user/syncthing.service"
        mode: 0644
      notify: systemd user restart
      tags:
        - unit

    - name: Systemd
      become: true
      become_method: ansible.builtin.runas
      become_user: "{{ syncthing_user }}"
      ansible.builtin.systemd_service:
        name: syncthing.service
        daemon_reload: true
        enabled: true
        # state: started
        scope: user
      tags:
        - service

- name: Global system unit
  tags:
    - syncthing
    - systemd
  when:
    - syncthing_systemd_user is not defined or
      not syncthing_systemd_user
  block:
    - name: user
      ansible.builtin.user:
        name: "{{ syncthing_user }}"
        system: true
        create_home: true
      tags:
        - user

    - name: service
      ansible.builtin.systemd_service:
        name: "syncthing@{{ syncthing_user }}.service"
        enabled: true
        state: started
        daemon_reload: true
      tags:
        - service
