---
# tasks file for ssh
- include: "{{ ansible_os_family }}.yml"

- name: passwordauthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[#\s]*PasswordAuthentication\s+.*$'
    line: 'PasswordAuthentication {{ ssh_passwordauthentication | lower() }}'
    backup: yes
    validate: /usr/sbin/sshd -t -f %s
  when:
    - ssh_passwordauthentication is defined
    - ssh_passwordauthentication | lower() in [ 'yes', 'no' ]
  notify: ssh restart
  tags:
    - ssh
    - passwordauthentication

- name: gssapiauthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^[#\s]*GSSAPIAuthentication\s+.*$'
    line: 'GSSAPIAuthentication {{ ssh_gssapiauthentication | lower() }}'
    backup: yes
    backrefs: yes
    validate: /usr/sbin/sshd -t -f %s
  when:
    - ssh_gssapiauthentication is defined
    - ssh_gssapiauthentication | lower() in [ 'yes', 'no' ]
  notify: sshd restart
  tags:
    - ssh
    - gssapiauthentication
...
