---
# handlers file for syncthing
- name: restart
  systemd:
    name: 'syncthing@{{ syncthing_user }}.service'
    daemon_reload: yes

- name: apply sysctl settings
  command: 'sysctl -p {{ syncthing_sysctl_file }}'
...
